;;; xdg-paths-defaults.el --- Set paths to conform XDG spec -*- lexical-binding: t; -*-
;;
;; Version: 0.0.1
;; Package-Requires: ((cl-lib "0.5"))
;;
;;; Commentary:
;;
;; This package sets default paths according to the XDG Base Directory Specification.
;;
;;; Code:

(eval-when-compile
  (require 'cl-lib))

(require 'xdg-paths)

(cl-letf (((symbol-function 'cache)  (symbol-function #'xdg-paths-cache-home))
          ((symbol-function 'config) (symbol-function #'xdg-paths-config-home))
          ((symbol-function 'data)   (symbol-function #'xdg-paths-data-home))
          ((symbol-function 'state)  (symbol-function #'xdg-paths-state-home)))
  (with-no-warnings  ; suppress `reference to free variable` warnings
    (setq-default
     abbrev-file-name                         (config "abbrev.el")
     auto-insert-directory                    (config "insert")
     auto-save-list-file-prefix               (cache "auto-save-list/.saves-")
     backup-directory-alist                   (list (cons "." (cache "backup")))
     bookmark-default-file                    (state "bookmark-default.el")
     calc-settings-file                       (config "calc-settings.el")
     custom-file                              (config "custom.el")
     custom-theme-directory                   (xdg-paths-config-home)
     desktop-dirname                          (xdg-paths-cache-home)
     desktop-path                             (list desktop-dirname)
     diary-file                               (config "diary")
     ecomplete-database-file                  (state "ecomplete-database.el")
     ede-project-placeholder-cache-file       (cache "ede-projects.el")
     erc-dcc-get-default-directory            (state "erc/dcc/")
     erc-log-channels-directory               (state "erc/log-channels/")
     erc-startup-file-list                    (list (data "erc/startup.el") (data "erc/startup") ".ercrc.el" ".ercrc")
     eshell-aliases-file                      (config "eshell/aliases")
     eshell-directory-name                    (cache "eshell/")
     eshell-login-script                      (config "eshell/login")
     eshell-rc-script                         (config "eshell/profile")
     eudc-options-file                        (data "eudc-options.el")
     eww-bookmarks-directory                  (state "eww/")
     filesets-menu-cache-file                 (cache "filesets-menu-cache.el")
     gamegrid-user-score-file-directory       (state "gamegrid-user-score/")
     gnus-cache-directory                     (cache "news")
     gnus-dribble-directory                   (state "gnus/dribble/")
     gnus-init-file                           (data "gnus/init.el")
     gnus-startup-file                        (data "gnus/newsrc")
     ido-save-directory-list-file             (state "ido-save-directory-list.el")
     ielm-history-file-name                   (state "ielm-history.eld")
     image-dired-dir                          (cache "image-dired/")
     Info-saved-history-file                  (state "info-saved-history.eld")
     kkc-init-file-name                       (state "kkc-init.el")
     multisession-directory                   (state "multisession/")
     native-compile-target-directory          (cache "eln/")
     newsticker-cache-filename                (cache "newsticker/cache.el")
     newsticker-dir                           (state "newsticker/data/")
     nsm-settings-file                        (state "nsm-settings.el")
     org-clock-persist-file                   (state "org-clock-save.el")
     org-id-locations-file                    (state "org-id-locations.el")
     org-persist-directory                    (state "org-persist/")
     org-publish-timestamp-directory          (state "org-timestamps/")
     package-quickstart-file                  (cache "package-quickstart.el")
     package-user-dir                         (cache "elpa")
     persist--directory-location              (state "persist/")
     project-list-file                        (state "project-list.el")
     quickurl-url-file                        (state "quickurl-url.el")
     rcirc-log-directory                      (state "rcirc-log/")
     recentf-save-file                        (state "recentf-save.el")
     remember-data-directory                  (state "remember/data.d/")
     remember-data-file                       (state "remember/data")
     save-place-file                          (state "save-place.el")
     savehist-file                            (state "savehist.el")
     semanticdb-default-save-directory        (state "semantic/")
     server-auth-dir                          (cache "server/")
     shadow-info-file                         (state "shadow/info.el")
     shadow-todo-file                         (state "shadow/todo.el")
     shared-game-score-directory              (state "shared-game-score/")
     srecode-map-save-file                    (state "srecode-map.el")
     timeclock-file                           (state "timeclock")
     tramp-auto-save-directory                (cache "tramp/auto-save/")
     tramp-persistency-file-name              (state "tramp/persistency.el")
     type-break-file-name                     (state "type-break.el")
     url-cache-directory                      (cache "url/cache/")
     url-configuration-directory              (state "url/")
     url-cookie-file                          (state "url/cookies.el")
     url-history-file                         (state "url/history.el")
     ;;; Third-party packages
     abm-file                                 (state "autobookmarks.el")
     ac-comphist-file                         (state "ac-comphist.el")
     amx-save-file                            (state "amx-save.el")
     anaconda-mode-installation-directory     (state "anaconda-mode/")
     annotate-file                            (state "annotations.el")
     async-byte-compile-log-file              (state "async-bytecomp.log")
     auto-package-update-last-update-day-path (cache "auto-package-update-last-update-day")
     aya-persist-snippets-dir                 (config "snippets")
     bbdb-file                                (state "bbdb/bbdb.el")
     bbdb-vcard-directory                     (state "bbdb/vcard/")
     binky-cache-directory                    (cache "binky/cache/")
     blamer-avatar-folder                     (state "blamer/avatars/")
     bm-repository-file                       (state "bm-repository.el")
     bmkp-bmenu-commands-file                 (state "bmkp/bmenu-commands.el")
     bmkp-current-bookmark-file               (state "bmkp/current-bookmark.el")
     bmkp-last-bookmark-file                  (state "bmkp/last-bookmark.el")
     bookiez-file                             (state "bookiez")
     cider-repl-history-file                  (state "cider-repl-history.el")
     clm/logging-dir                          (state "command-log-mode/logging/")
     code-review-db-database-file             (state "code-review/database.sqlite")
     code-review-download-dir                 (state "code-review/downloads/")
     code-review-log-file                     (state "code-review/log")
     company-dict-dir                         (config "dict/")
     company-statistics-file                  (state "company-statistics.el")
     company-tabnine-binaries-folder          (cache "company-tabnine-binaries")
     conventional-changelog-tmp-dir           (state "conventional-changelog/")
     copilot-install-dir                      (cache "copilot/")
     dap-breakpoints-file                     (state "dap/breakpoints.el")
     dap-java-test-runner                     (state "lsp-java/eclipse.jdt.ls/test-runner/junit-platform-console-standalone.jar")
     dap-utils-extension-path                 (state "dap/extensions/")
     dape-adapter-dir                         (state "dape-adapters/")
     debbugs-gnu-persistency-file             (state "debbugs.el")
     detached-db-directory                    (state "detached/db/")
     detached-session-directory               (state "detached/sessions/")
     devdocs-browser-cache-directory          (cache "devdocs-browser/")
     devdocs-data-dir                         (cache "devdocs/")
     dired-recent-directories-file            (state "dired-recent-directories.el")
     dirvish-cache-dir                        (cache "dirvish/")
     efar-state-file-name                     (state "efar-state.eld")
     elbank-data-file                         (state "elbank-data.el")
     elfeed-autotag-files                     (list (data "elfeed/autotags.org"))
     elfeed-db-directory                      (state "elfeed/db/")
     elfeed-enclosure-default-dir             (state "elfeed/enclosures/")
     elfeed-score-rule-stats-file             (state "elfeed/score/score-rule-stats.eld")
     elfeed-score-score-file                  (data "elfeed/score/score.el")
     elgrep-data-file                         (state "elgrep-data.el")
     elisp-autofmt-cache-directory            (cache "elisp-autofmt/cache/")
     elmo-msgdb-directory                     (state "elmo/")
     elmo-split-log-file                      (state "elmo/split-log")
     elpher-bookmarks-file                    (state "elpher-bookmarks.el")
     emacs-gc-stats-file                      (state "emacs-gc-stats.eld")
     ement-sessions-file                      (state "ement-sessions.el")
     emms-directory                           (state "emms/")
     emojify-emojis-dir                       (state "emojify/")
     epkg-repository                          (state "epkgs/")
     equake-persistent-display-file           (state "equake-persistent-display")
     evil-tutor-working-directory             (state "evil-tutor")
     fontaine-latest-state-file               (state "fontaine-latest-state.eld")
     forge-database-file                      (state "forge/database.sqlite")
     forge-post-directory                     (state "forge/posts/")
     geben-temporary-file-directory           (state "geben/")
     geiser-repl-history-filename             (state "geiser/repl-history")
     gnus-notes-file                          (state "gnus-notes/articles.el")
     gnus-notes-top-dir                       (state "gnus-notes/")
     gptel-crowdsourced-prompts-file          (cache "gptel-crowdsourced-prompts.csv")
     grammalecte-settings-file                (data "grammalecte-settings.el")
     hackernews-visited-links-file            (state "hackernews/visited-links.el")
     harpoon-cache-file                       (cache "harpoon/")
     helm-adaptive-history-file               (state "helm/adaptive-history.el")
     helm-backup-path                         (state "helm/backup/")
     helm-github-stars-cache-file             (cache "helm/github-stars-cache.el")
     helm-net-curl-log-file                   (state "helm/helm-curl.log")
     historian-save-file                      (state "historian-save.el")
     indium-workspace-file                    (state "indium/workspaces.el")
     irfc-directory                           (state "irfc/")
     irony-user-dir                           (state "irony/")
     jabber-avatar-cache-directory            (cache "jabber/avatar-cache")
     jabber-history-dir                       (state "jabber/history")
     keyfreq-file                             (state "keyfreq.el")
     keyfreq-file-lock                        (state "keyfreq.lock")
     libbcel-oauth-store-filename             (state "libbcel-oauth-store.el.gpg")
     litable-list-file                        (state "litable-list.el")
     logview-cache-filename                   (cache "logview-cache")
     logview-views-file                       (data "logview-views")
     lookup-init-directory                    (data "lookup/")
     lsp-clojure-workspace-dir                (state "lsp-clojure/workspace/")
     lsp-eslint-library-choices-file          (state "lsp/eslint-library-choices.el")
     lsp-java-server-install-dir              (state "lsp-java/eclipse.jdt.ls/server/")
     lsp-java-workspace-dir                   (state "lsp-java/workspace/")
     lsp-ltex-user-rules-path                 (state "lsp-ltex/")
     lsp-python-ms-dir                        (state "lsp-python-ms/")
     lsp-server-install-dir                   (cache "lsp-server/")
     lsp-session-file                         (state "lsp-session.el")
     magit-commit-mark-directory              (state "magit-commit-mark/")
     magithub-cache-file                      (cache "magithub/cache.el")
     magithub-dir                             (state "magithub/")
     mastodon-client--token-file              (state "mastodon-client--token")
     mc/list-file                             (state "mc-list.el")
     meghanada-server-install-dir             (state "meghanada/")
     multi-compile-history-file               (state "multi-compile-history.el")
     nix-buffer-directory-name                (state "nix-buffer/")
     nomad-tramp-script-directory             (state "nomad-tramp/")
     notmuch-init-file                        (data "notmuch-init") ;; MUST NOT end with ".el"
     nov-save-place-file                      (state "nov-save-place.el")
     omnisharp-cache-directory                (cache "omnisharp/cache")
     org-caldav-backup-file                   (state "org-caldav/backup.org")
     org-default-notes-file                   (data "notes.org")
     org-directory                            (data "org/")
     org-gcal-dir                             (state "org-gcal/")
     org-journal-cache-file                   (cache "org-journal-cache.el")
     org-node-fakeroam-data-dir               (state "org-node-fakeroam/")
     org-recent-headings-save-file            (state "org-recent-headings.el")
     org-registry-file                        (state "org-registry.el")
     org-roam-db-location                     (cache "org-roam.db")
     org-roam-directory                       (data "org-roam/")
     package-quickstart-file                  (state "package-quickstart.el")
     pandoc-data-dir                          (data "pandoc-mode/")
     pcache-directory                         (cache "pcache/")
     pdf-view-restore-filename                (state "pdf-view-restore.el")
     persist--directory-location              (state "persist/")
     persistent-scratch-save-file             (state "persistent-scratch.el")
     persp-save-dir                           (state "persp-mode/")
     pomm-state-file-location                 (state "pomm/")
     pomm-third-time-state-file-location      (state "pomm-third-time/")
     prescient-save-file                      (state "prescient-save.el")
     projectile-cache-file                    (cache "projectile.cache")
     projectile-known-projects-file           (state "projectile-bookmarks.eld")
     psession-elisp-objects-default-directory (state "psession/")
     purpose-default-layout-file              (data "window-purpose/default-layout.el")
     purpose-layout-dirs                      (list (data "window-purpose/layouts/"))
     pyim-dcache-directory                    (cache "pyim/dcache/")
     quack-dir                                (state "quack/")
     racket-repl-command-file                 (data "racket-mode/repl.rkt")
     racket-repl-history-directory            (state "racket-mode/repl-history/")
     request-storage-directory                (cache "request/storage/")
     rfc-mode-directory                       (state "rfc-mode/")
     rime-user-data-dir                       (state "rime/")
     rmh-elfeed-org-files                     (list (config "elfeed.org"))
     runner-init-file                         (state "runner-init.el")
     save-kill-file-name                      (state "save-kill.el")
     save-visited-files-location              (state "save-visited-files-location")
     session-save-file                        (state "session.el")
     shell-maker-history-path                 (state "shell-maker/")
     sly-mrepl-history-file-name              (state "sly/mrepl-history")
     smex-save-file                           (state "smex-save.el")
     speed-type-gb-dir                        (state "speed-type/")
     spell-fu-directory                       (state "spell-fu/")
     streak-file                              (state "streak.json")
     svg-lib-icons-dir                        (state "svg-lib/icons/")
     sx-cache-directory                       (cache "sx/cache/")
     tempel-path                              (config "tempel/templates.eld")
     tabspaces-session-file                   (state "tabspaces-session.eld")
     tldr-directory-path                      (state "tldr/")
     transient-history-file                   (state "transient/history.el")
     transient-levels-file                    (state "transient/levels.el")
     transient-values-file                    (state "transient/values.el")
     treemacs-last-error-persist-file         (cache "treemacs-persist-last-error")
     treemacs-persist-file                    (cache "treemacs-persist")
     undo-fu-session-directory                (state "undo-fu-session/")
     undohist-directory                       (state "undohist/")
     uptimes-database                         (state "uptimes.el")
     user-emacs-ensime-directory              (state "ensime/")
     vimish-fold-dir                          (state "vimish-fold/")
     virtual-comment-default-file             (state "virtual-comments.el")
     wl-address-file                          (data "wanderlust/address")
     wl-alias-file                            (data "wanderlust/alias")
     wl-folders-file                          (data "wanderlust/folders")
     wl-init-file                             (data "wanderlust/init.el")
     wl-temporary-file-directory              (cache "wanderlust/")
     wl-x-face-file                           (data "wanderlust/x-face")
     x86-lookup-cache-directory               (cache "x86-lookup/cache/")
     xkcd-cache-dir                           (cache "xkcd/")
     yas-snippet-dirs                         (list aya-persist-snippets-dir))
    (add-to-list 'native-comp-eln-load-path native-compile-target-directory)))

(provide 'xdg-paths-defaults)
;;; xdg-paths-defaults.el ends here
